### ISSUE TITLE
List of Id's

### ISSUE THREAD

**Issue by ChristopherArnold28** [scaratozzolo/MouseTools#2]
I find the work you've done here extremely useful. I'm doing some work attempting to gather disney wait times and do some analysis followed by doing some live predictions on wait times. I had issues sourcing the wait times as I started first with looking for web sites to scrape but hoping that those web sites would maintain their wait times as new rides were added proved to be futile. 

As I'm looking through your work, I notice you have a list of Id's for attractions, parks, and the works. Instead of just copying your work I'm attempting to recreate it and am wondering how you got this list of Id's. Where did they come from and how did you source them?

**Comment by scaratozzolo** [comment]
I am also trying to do something similar, which is why I made this project.

I managed to find Disney's backend api using a request interceptor. I then created a script using recursion to crawl the whole api and grab all the links it could find. After looking at all the links I saw a pattern in the URLs so I created another script that parsed the links into ID's. 

It's also possible to get all the IDs by using this package. I haven't had time to update it or create documentation since school started, but hopefully soon.
